/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentaAutomoviles.c1_Presentacion;

/**
 *
 * @author AMARO
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FormMenu() {
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        ItemGestionarProducto = new javax.swing.JMenu();
        gestionarProducto = new javax.swing.JMenuItem();
        gestionarMesa = new javax.swing.JMenuItem();
        gestionarCliente = new javax.swing.JMenuItem();
        gestionarCocinero = new javax.swing.JMenuItem();
        programacionDeMenus = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        registrarPedido = new javax.swing.JMenuItem();
        generarComprobante = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        reporteDeVentas = new javax.swing.JMenuItem();
        reporteDeProductos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        gestionarUsuarios = new javax.swing.JMenuItem();
        gestionarPermisos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        ayuda = new javax.swing.JMenuItem();
        acercade = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ItemGestionarProducto.setText("Gestionar Programacion");

        gestionarProducto.setText("Gestionar Producto");
        gestionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarProductoActionPerformed(evt);
            }
        });
        ItemGestionarProducto.add(gestionarProducto);

        gestionarMesa.setText("Gestionar Mesa");
        gestionarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarMesaActionPerformed(evt);
            }
        });
        ItemGestionarProducto.add(gestionarMesa);

        gestionarCliente.setText("Gestionar Cliente");
        gestionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarClienteActionPerformed(evt);
            }
        });
        ItemGestionarProducto.add(gestionarCliente);

        gestionarCocinero.setText("Gestionar Cocinero");
        gestionarCocinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarCocineroActionPerformed(evt);
            }
        });
        ItemGestionarProducto.add(gestionarCocinero);

        programacionDeMenus.setText("Programacion de menus");
        programacionDeMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programacionDeMenusActionPerformed(evt);
            }
        });
        ItemGestionarProducto.add(programacionDeMenus);

        jMenuBar1.add(ItemGestionarProducto);

        jMenu3.setText("Gestionar Pedidos");

        registrarPedido.setText("Registrar Pedido");
        registrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarPedidoActionPerformed(evt);
            }
        });
        jMenu3.add(registrarPedido);

        generarComprobante.setText("Generar Comprobante");
        generarComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarComprobanteActionPerformed(evt);
            }
        });
        jMenu3.add(generarComprobante);
        jMenu3.add(jSeparator3);

        reporteDeVentas.setText("Reporte de Ventas");
        reporteDeVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteDeVentasActionPerformed(evt);
            }
        });
        jMenu3.add(reporteDeVentas);

        reporteDeProductos.setText("Reporte de Productos");
        reporteDeProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteDeProductosActionPerformed(evt);
            }
        });
        jMenu3.add(reporteDeProductos);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Seguridad");

        gestionarUsuarios.setText("Gestionar Usuarios");
        gestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(gestionarUsuarios);

        gestionarPermisos.setText("Gestionar Pemisos");
        gestionarPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarPermisosActionPerformed(evt);
            }
        });
        jMenu2.add(gestionarPermisos);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("RestauranteSoft");

        ayuda.setText("Ayuda");
        ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaActionPerformed(evt);
            }
        });
        jMenu1.add(ayuda);

        acercade.setText("Acerca de");
        acercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercadeActionPerformed(evt);
            }
        });
        jMenu1.add(acercade);
        jMenu1.add(jSeparator1);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu1.add(salir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarProductoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_gestionarProductoActionPerformed

    private void gestionarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarMesaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_gestionarMesaActionPerformed

    private void gestionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarClienteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_gestionarClienteActionPerformed

    private void gestionarCocineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarCocineroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_gestionarCocineroActionPerformed

    private void programacionDeMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programacionDeMenusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_programacionDeMenusActionPerformed

    private void registrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarPedidoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_registrarPedidoActionPerformed

    private void generarComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarComprobanteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_generarComprobanteActionPerformed

    private void reporteDeVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteDeVentasActionPerformed
        // TODO add your handling code here
       
    }//GEN-LAST:event_reporteDeVentasActionPerformed

    private void reporteDeProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteDeProductosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_reporteDeProductosActionPerformed

    private void gestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionarUsuariosActionPerformed

    private void gestionarPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarPermisosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionarPermisosActionPerformed

    private void ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ayudaActionPerformed

    private void acercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acercadeActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ItemGestionarProducto;
    private javax.swing.JMenuItem acercade;
    private javax.swing.JMenuItem ayuda;
    private javax.swing.JMenuItem generarComprobante;
    private javax.swing.JMenuItem gestionarCliente;
    private javax.swing.JMenuItem gestionarCocinero;
    private javax.swing.JMenuItem gestionarMesa;
    private javax.swing.JMenuItem gestionarPermisos;
    private javax.swing.JMenuItem gestionarProducto;
    private javax.swing.JMenuItem gestionarUsuarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem programacionDeMenus;
    private javax.swing.JMenuItem registrarPedido;
    private javax.swing.JMenuItem reporteDeProductos;
    private javax.swing.JMenuItem reporteDeVentas;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
